kind = "web"
previewPath = "/"
title = "Système d'Archivage"
version = "1.0.0"
id = "artifacts/archivage-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26198

[services.development]
run = "pnpm --filter @workspace/archivage-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/archivage-app", "run", "build" ]
publicDir = "artifacts/archivage-app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26198"
BASE_PATH = "/"
